baseurl = "http://s-aguinaga.github.io/"
languageCode = "en-us"
title = "Sal Aguinaga"
theme = "hugo-strata"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = "UA-35842456-1"
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Sal Aguinaga"
	description = "Describe your website"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "PhD student in CS interested in statistical modeling, machine learning, nlp, graph and information theory." 
		# The icons will be shown if you enter your username
		twitter = "abitofalchemy"
		github =  "abitofalchemy"
    #googlescholar="eFooqC4AAAAJ&hl=en&oi=ao"
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = "https://www.linkedin.com/in/salvador-aguinaga-767a62"

		copyright = [
			"&copy; S. Aguinaga | Design: [HTML5 UP](//html5up.net)"
#			"Demo Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = false
		title = "About"
		content = "I am a CS PhD candidate in the Department of Computer Science and Engineering at the University of Notre Dame. My research centers on developing mathematical abstractions and algorithms to study complex information networks. Currently I am working on generative network models that combines methods in natural language processing with graph theory to learn the grammars of networks. Previous work includes stints in auditory research and electro-physiology at Northwestern University as well as stints as a hardware EE at Motorola (mobile devices) and 3Com (now, HPE Networking). <br>In my *free time* you'll find me fixing my house, running, sailing (less frequently nowawdays), and spending time with friends, but most importantly with family, who are always reminding me to maintain a good sense of humor."

	[params.news]
    title="News"
    content3="- 16Aug16 - Got an invite to attend this year's [Heildelberg Laureate Forum](http://www.heidelberg-laureate-forum.org)"
    content2="- 13Aug16 - The Infinity Mirror Test for Analyzing the Robustness of Graph Generators  [ABSTRACT](http://www.mlgworkshop.org/2016/paper/MLG2016_paper_17.pdf)"
    #content2="- 19Jul16 - My collaborators and I got a paper accepted at [CIKM2016](http://cikm2016.cs.iupui.edu)!"
    content1="- 13Jun16 - We got a paper accepted the [MLG2016](http://www.mlgworkshop.org/2016/), a workshop at KDD2016 in SF.!"   
    content0="- More in the Blog section"
    # 04May16 - PhD candidacy defense 'Generative Network Models from Hyperedge Replacement Grammars'"

	[params.portfolio]
		hide  = false
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/img0.jpg"
      thumb = "thumbs/img0.jpg"
      title = "Growing Graphs w/ HRGs, a new graph generator."
      description = "Discovering the underlying structures present in large real-world graphs."

    [[params.portfolio.gallery]]
      image = "fulls/img1.jpg"
      thumb = "thumbs/img1.jpg"
      title = "The Infinity Mirror Test (MLG2016)"
      description = "Presented this work at SIGKDD's  Workshop on Mining and Learning with Graphs, San Francisco, CA, August 2016."



	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "Feel free to email me or contact me via a social media platform."

		address = [
			"Office:",
			"84K Nieuwland Science Hall",
      "Notre Dame, Indiana",
      "United States"
		]
		phone = "000-000-0000"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "saguinag@nd.edu"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 10

[[menu.main]]
	name = "CV"
	url  = "pages/Sept2016_saguinaga_cv.pdf"
	weight = 1
